<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ServerAdminSimulator.ModSDK</AssemblyName>
    <RootNamespace>ServerAdminSimulator.ModSDK</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>8.0</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\ServerAdminSimulator.ModSDK.xml</DocumentationFile>
    <Description>Official Modding SDK for Server-Admin Simulator by Ice-Phoenix</Description>
    <Authors>Ice-Phoenix</Authors>
    <Version>1.2.0</Version>
    <PackageProjectUrl>https://github.com/TitanEch0/ServerAdminSimulator-ModSDK</PackageProjectUrl>
  </PropertyGroup>
</Project>
